title: RSS Reader
description: Combind some interesting information
author: bGZo

# Handling Reading
encoding            : utf-8
exclude:
  - node_modules
  - package-lock.json
  - package.json
  - test
  - config
  - utils
  - tailwind.config.js

# Filtering Content
future              : true

# Conversion
markdown            : kramdown
highlighter         : rouge

# Outputting
permalink           : :year/:month/:day.html
timezone            : Asia/Singapore

# Markdown Processors
kramdown:
  hard_wrap         : true
  show_warnings     : true
