name: sync

on:
  workflow_dispatch:
  push:
    branches: [ rss_reader ]
  schedule:
    - cron:  '0 21 * * *'

jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r utils/requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Run Script
        run: |
          python3 utils/sync.py

      - name: Run Safe Dir
        run: |
          git config --global --add safe.directory /github/workspace

      - name: Push Articles
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name bgzo
            git config user.email bgzo@outlook.com
            git add .
            git commit -m "Sync Feed"
            git push
          else
            echo "no changes";
          fi